### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Luchanso** [Luchanso/react-has-mounted#1]
Need for release:
* [x] Tests
* [ ] Typescript
* [x] Babel for IE11 code
* [ ] change namings hasMounted -> hocHasMounted
* [ ] Add apart render props component
* [ ] Make API more simple
